Feature/custom buttons remote
YIO-Remote/integrations.library pull request #12
Opened 2020-09-04 11:30 UTC by nikos1988

PR 2/3

2020-09-05 09:40 UTC, zehnm requested changes
Thanks for your contribution!
Please add a pull request description, what this changes are for. Especially for the new `sendCustomCommand` method.

2020-09-05 09:40 UTC, zehnm commented on src/yio-plugin/integration.cpp
> +    qWarning() << "send custom command not implemented";
Please use the category logger: `qCWarning(m_logCategory) << ...`

2020-09-05 09:40 UTC, zehnm commented on src/yio-interface/integrationinterface.h
> +     */
Either document method or remove empty template.
Yes, there are other empty doc templates in this class which need to be fixed... But new code should be better ;-)

2020-09-05 09:40 UTC, zehnm commented on src/yio-interface/integrationinterface.h
> +     */
See above

2020-09-05 09:40 UTC, zehnm commented on src/yio-interface/integrationinterface.h
> +    virtual void sendCustomCommand(const QString& type, const QString& entityId, int commandIndex,
Why is `sendCustomCommand` required what `sendCommand` can't handle?
Couldn't it be integrated in `sendCommand` with additional information in `param`?

2020-09-06 09:13 UTC, nikos1988 commented
Hi, could you take another look at the two commits i added. I think supporting the custom features is possible with minimal changes to the addAvailableEntity method. (Added customFeatures string list parameter with empty list as default)

2020-09-06 19:45 UTC, zehnm commented
@nikos1988 I'll have a look tomorrow. I didn't see the 3rd part of your PR, maybe I just missed it. Shouldn't there be an implementation in an integration plugin, e.g. home-assistant, openhab or homey?
I saw a mqtt reference in your other PR. What's that for, an upcoming mqtt integration?

2020-09-07 06:21 UTC, nikos1988 commented
> 
> @nikos1988 I'll have a look tomorrow. I didn't see the 3rd part of your PR, maybe I just missed it. Shouldn't there be an implementation in an integration plugin, e.g. home-assistant, openhab or homey?
> I saw a mqtt reference in your other PR. What's that for, an upcoming mqtt integration?

Hi, the 3rd PR was for the web-configurator to add the custom features. I have developed an mqtt integration, but this is currently customized for my own needs. Maybe i can release something better suited for everyone in the future.

2020-09-07 20:36 UTC, zehnm commented
> I have developed an mqtt integration, but this is currently customized for my own needs.

Maybe we can join our efforts: I'm working on a webhook integration which would be very easy to extend with mqtt:
https://github.com/zehnm/integration.webhook
I've already thought of enhancing it with mqtt, since most logic could be used for webhook & mqtt, but haven't had time to continue working on it.

2021-01-11 20:26 UTC, zehnm commented
Since there hasn't been any activity for a while and the PR looks ready, I'm going to change the state to ready and review it.

2021-01-11 20:37 UTC, zehnm approved these changes

2021-01-11 20:41 UTC, merged